name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:14
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #     ports:
    #       - 5434:5432
    #     # volumes:
    #     #   - ./init_scripts/postgres/:/docker-entrypoint-initdb.d/
    #   mongo:
    #     image: mongo:6.0
    #     env:
    #       MONGO_INITDB_ROOT_USERNAME: mongodb
    #       MONGO_INITDB_ROOT_PASSWORD: mongodb
    #     ports:
    #       - 27019:27017

    steps:
      - run: ls -la .
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: pip install poetry
      - run: poetry config virtualenvs.create false --local
      - run: poetry install
      - run: make test
